version: '3.3'
services:
  database:
    image: mysql:latest
    volumes:
       - "./sql-scripts:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: webster_dictionary
    ports:
      - "3306:3306"
