name: Releases

on: push

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v3
       - uses: actions/setup-go@v4
         with:
           go-version: '1.20.6'
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
       - name: Build tar
         run: |
           make docker-binaries
       - name: Check pwd 
         run: pwd
       - name: Check ls 
         run: | 
           ls
           ls -l
       - name: Check home 
         run: | 
           cd
           ls -l
           cd $HOME
           ls -l
       - name: Check / 
         run: | 
           cd /
           cd ./bin
           ls -l

  # on:
  #   push:
  #     tags:
  #       - "v*.*.*"
  # 
  # permissions:
  #   contents: write
  # 
  # jobs:
  #   build:
  #     runs-on: ubuntu-latest
  #     steps:
  #       - name: Checkout
  #         uses: actions/checkout@v3
  #       - uses: actions/setup-go@v4
  #         with:
  #           go-version: '1.20.6'
  #       - name: Set up Docker Buildx
  #         uses: docker/setup-buildx-action@v2
  #       - name: Build docker binaries
  #         run: |
  #           make docker-binaries
  #       - name: Release
  #         uses: softprops/action-gh-release@v1
  #         if: startsWith(github.ref, 'refs/tags/')
  #         with:
  #           files: |
  #              /home/runner/work/macaw/macaw/bin/macaw-windows-amd64
  #              /home/runner/work/macaw/macaw/bin/macaw-darwin-amd64
  #              /home/runner/work/macaw/macaw/bin/macaw-linux-amd64
