name: Releases

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.6'
      - name: Install fyne-cross
        run: go install github.com/fyne-io/fyne-cross@latest
      - name: Build tar
        run: make linux
      - name: Release
        uses: softprops/action-gh-release@v1
          # TODO: Use this after we settle on the proper gh workflow.
          # if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./fyne-cross/dist/linux-amd64
